import { Button, Loading, ImagePreview, Switch, Col, Row, Rate, Uploader, Tabbar, TabbarItem, NavBar, Image, Toast, Search, Swipe, SwipeItem, Grid, GridItem, Icon, Lazyload, ActionSheet, Dialog, Checkbox, Tab, Tabs } from 'vant'
import Vue from 'vue'
Vue.use(Toast)
Vue.use(NavBar)
Vue.use(Button)
Vue.use(Switch)
Vue.use(Rate)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(GridItem)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(Icon)
Vue.use(Lazyload)
Vue.use(ActionSheet)
Vue.use(Dialog)
Vue.use(Checkbox)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Uploader)
Vue.use(Image)
Vue.use(Row)
Vue.use(Col)
Vue.use(ImagePreview)
Vue.use(Loading)
